### ISSUE TITLE
Duda

### ISSUE THREAD

**Issue by JMB-DAM** [JMB-DAM/practica_dwec_gestor_presupuesto#1]
https://github.com/JMB-DAM/practica_dwec_gestor_presupuesto/blob/f4f3cdd3ca34a787784d71b7bc578cf17d33e6f4/js/gestionPresupuesto.js#L39

Hola @pedroprieto,

No se porque no me pasa el test:
Función CrearGasto y funcionamiento de objeto gasto
    1) CrearGasto devuelve objeto gasto si los parámetros son correctos

**Comment by pedroprieto** [comment]
Buenas,

No estás utilizando el método de constructor: la función `CrearGasto` debe ser una función constructora que se utilizará con `new`. Al crear un objeto literal:
https://github.com/JMB-DAM/practica_dwec_gestor_presupuesto/blob/f4f3cdd3ca34a787784d71b7bc578cf17d33e6f4/js/gestionPresupuesto.js#L21-L35

no estás haciendo uso de la función constructora. Debes crear las propiedades con `this`. Repasa la teoría sobre el tema.

Un saludo!!

**Comment by JMB-DAM** [comment]
Resuelto! Mi confusión se generó en que estaba pasando a la función CrearGasto los parámetros con dos nombres que no eran correctos, y de ahí generó en hacer cosas que no estaban bien.

Gracias!! Un saludo
